
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar/navBar";
import Aos from "@/Components/Aos.jsx";
import { NextAuthProvider } from "./helper/providers";
import { CartProvider } from "@/Components/CartContext/cart";
import Footer from "@/Components/footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
     

        <NextAuthProvider>
          <CartProvider>
          <Aos />
          <Navbar />
          {children}
          </CartProvider>
          <Footer/>
        </NextAuthProvider>
      
      </body>
    </html>
  );
}
